config/routes.rb
Rails.application.routes.draw do

  resources :specials
  resources :homes do
    resources :visits
  end
 resources :contact
 resources :pricing

  resources :dashboards
  resources :posts
  get 'welcome/index'
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'welcome#index'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :home
  belongs_to :user

  #enums
enum tap: [:tap_yes, :tap_no, :tap_na]
enum toilet: [:toilet_yes, :toilet_no, :toilet_na]
enum thermostat: [:thermostat_yes, :thermostat_no, :thermostat_na]
enum walkaround: [:walkaround_yes, :walkaround_no, :walkaround_na]
enum damage: [:damage_yes, :damage_no, :damage_na]
enum car: [:car_start, :car_move, :car_no, :car_na] 
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
    @home = Home.find_by(params[:id])
    @home2 = Home.find(params[:home_id])
    @homeid = @home.id
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)
    @home2 = Home.find_by(params[:id])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to home_visits_path(@home2, @visit), notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to home_visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:toilet, :tap, :car, :thermostat, :walkaround, :damage, :note, :visittime, :home_id, :user_id, home_attributes: [:home_id, :id])
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= simple_form_for @visit, url: home_visits_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :toilet, collection: [["yes", :toilet_yes],["no", :toilet_no],["n/a", :toilet_na]], as: :radio_buttons %>
    <%= f.input :tap, collection: [["yes", :tap_yes],["no", :tap_no],["n/a", :tap_na]], as: :radio_buttons %>
    <%= f.input :car, collection: [["Started", :car_start], ["Started and Moved", :car_move],["no", :car_no],["n/a", :car_na]], as: :radio_buttons %>
    <%= f.input :thermostat, collection: [["yes", :thermostat_yes],["no", :thermostat_no],["n/a", :thermostat_na]], as: :radio_buttons %>
    <%= f.input :walkaround, collection: [["yes", :walkaround_yes],["no", :walkaround_no],["n/a", :walkaround_na]], as: :radio_buttons %>
    <%= f.input :damage, collection: [["yes", :damage_yes],["no", :damage_no],["n/a", :damage_na]], as: :radio_buttons %>
    <%= f.input :note, as: :text %>
    <%= f.input :visittime %>
    <%= f.hidden_field :home_id, :value => @homeid %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<br><br>
<%=@home.inspect %>

app/views/visits/edit.html.erb
<div class="page-header">
  <%= link_to home_visits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to home_visit_path(@visit.home_id, @visit.id), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing visit</h1>
</div>

<%= render 'form' %>

app/views/visits/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">

<div class="page-header">
  <%= link_to new_home_visit_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Visit
  <% end %>
  <h1>Listing visits</h1>
</div>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Toilet</th>
            <th>Tap</th>
            <th>Car</th>
            <th>Thermostat</th>
            <th>Walkaround</th>
            <th>Damage</th>
            <th>Note</th>
            <th>Visittime</th>
            <th>Home</th>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @visits) do |visit| %>
            <td><%= visit.toilet %></td>
            <td><%= visit.tap %></td>
            <td><%= visit.car %></td>
            <td><%= visit.thermostat %></td>
            <td><%= visit.walkaround %></td>
            <td><%= visit.damage %></td>
            <td><%= visit.note %></td>
            <td><%= visit.visittime %></td>
            <td><%= visit.home %></td>
            <td><%= visit.user %></td>
            <td><%= link_to 'Show', home_visit_path(visit.home_id, visit.id) %></td>
        <td><%= link_to 'Edit', edit_home_visit_path(visit.home_id, visit.id) %></td>
        <td><%= link_to 'Destroy', home_visit_path(visit.home_id, visit.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>


</div></div></div>

app/views/visits/new.html.erb
<div class="page-header">
  <%= link_to home_visits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New visit</h1>
</div>

<%= render 'form' %>

app/views/visits/show.html.erb
<div class="page-header">
  <%= link_to home_visits_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_home_visit_path(@visit.home_id, @visit.id), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show visit</h1>
</div>

<dl class="dl-horizontal">
  <dt>Toilet:</dt>
  <dd><%= @visit.toilet %></dd>

  <dt>Tap:</dt>
  <dd><%= @visit.tap %></dd>

  <dt>Car:</dt>
  <dd><%= @visit.car %></dd>

  <dt>Thermostat:</dt>
  <dd><%= @visit.thermostat %></dd>

  <dt>Walkaround:</dt>
  <dd><%= @visit.walkaround %></dd>

  <dt>Damage:</dt>
  <dd><%= @visit.damage %></dd>

  <dt>Note:</dt>
  <dd><%= @visit.note %></dd>

  <dt>Visittime:</dt>
  <dd><%= @visit.visittime %></dd>

  <dt>Home:</dt>
  <dd><%= @visit.home.inspect %></dd>

  <dt>User:</dt>
  <dd><%= @visit.user.inspect %></dd>

</dl>