config/routes.rb
Rails.application.routes.draw do

  resources :specials
  resources :homes do
    resources :visits
  end
 resources :contact
 resources :pricing

  resources :dashboards
  resources :posts
  get 'welcome/index'
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'welcome#index'

end

app/models/special.rb
class Special < ActiveRecord::Base
  belongs_to :home
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
  before_action :set_special, only: [:show, :edit, :update, :destroy]

  # GET /specials
  # GET /specials.json
  def index
    @specials = Special.all
  end

  # GET /specials/1
  # GET /specials/1.json
  def show
  end

  # GET /specials/new
  def new
    @special = Special.new
  end

  # GET /specials/1/edit
  def edit
  end

  # POST /specials
  # POST /specials.json
  def create
    @special = Special.new(special_params)

    respond_to do |format|
      if @special.save
        format.html { redirect_to @special, notice: 'Special was successfully created.' }
        format.json { render :show, status: :created, location: @special }
      else
        format.html { render :new }
        format.json { render json: @special.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specials/1
  # PATCH/PUT /specials/1.json
  def update
    respond_to do |format|
      if @special.update(special_params)
        format.html { redirect_to @special, notice: 'Special was successfully updated.' }
        format.json { render :show, status: :ok, location: @special }
      else
        format.html { render :edit }
        format.json { render json: @special.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specials/1
  # DELETE /specials/1.json
  def destroy
    @special.destroy
    respond_to do |format|
      format.html { redirect_to specials_url, notice: 'Special was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_special
      @special = Special.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def special_params
      params.require(:special).permit(:title, :body, :home_id)
    end
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/views/specials/_form.html.erb
<%= simple_form_for(@special) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, as: :text %>
    <%= f.association :home %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/specials/edit.html.erb
<div class="page-header">
  <%= link_to specials_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @special, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing special</h1>
</div>

<%= render 'form' %>

app/views/specials/index.html.erb
<div class="page-header">
  <%= link_to new_special_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Special
  <% end %>
  <h1>Listing specials</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Body</th>
            <th>Home</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @specials) do |special| %>
            <td><%= special.title %></td>
            <td><%= special.body %></td>
            <td><%= special.home %></td>
            <td><%= link_to 'Show', special %></td>
        <td><%= link_to 'Edit', edit_special_path(special) %></td>
        <td><%= link_to 'Destroy', special, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/specials/new.html.erb
<div class="page-header">
  <%= link_to specials_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New special</h1>
</div>

<%= render 'form' %>

app/views/specials/show.html.erb
<div class="page-header">
  <%= link_to specials_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_special_path(@special), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show special</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @special.title %></dd>

  <dt>Body:</dt>
  <dd><%= @special.body %></dd>

  <dt>Home:</dt>
  <dd><%= @special.home %></dd>

</dl>