config/routes.rb
Rails.application.routes.draw do

  resources :specials
  resources :homes do
    resources :visits
  end
 resources :contact
 resources :pricing

  resources :dashboards
  resources :posts
  get 'welcome/index'
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'welcome#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
  belongs_to :user
  has_many :specials
  has_many :visits
geocoded_by :address, :latitude  => :lat, :longitude => :lng
after_validation :geocode 

def address
  [street, city, state, zipcode].compact.join(', ')
end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
    @home.user_id = current_user.id
    @visit = @home.visits.build
  end

  # GET /homes/1/edit
  def edit
    @user = current_user
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:street, :city, :zipcode, :lat, :lng, :state, :user_id, users_attributes: [:user_id, :id])
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @home.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h4>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user_id, value: current_user.id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :street, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :street, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>
   <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div> 
  <div class="form-group">
    <%= f.label :zipcode, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :zipcode, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lat, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lat, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lng, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lng, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/homes/edit.html.erb
<div class="page-header">
  <%= link_to homes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @home, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing home</h1>
</div>

<%= render 'form' %>

app/views/homes/index.html.erb
<div class="page-header">
  <%= link_to new_home_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Home
  <% end %>
  <h1>Listing homes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th>Street</th>
            <th>City</th>
            <th>Zipcode</th>
            <th>Lat</th>
            <th>Lng</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @homes) do |home| %>
            <td><%= home.user.firstname %></td>
            <td><%= home.street %></td>
            <td><%= home.city %></td>
            <td><%= home.zipcode %></td>
            <td><%= home.lat %></td>
            <td><%= home.lng %></td>
            <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/homes/new.html.erb
<div class="page-header">
  <%= link_to homes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New home</h1>
</div>

<%= render 'form' %>

app/views/homes/show.html.erb
<div class="page-header">
  <%= link_to homes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_home_path(@home), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show home</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @home.user.inspect %></dd>

  <dt>Street:</dt>
  <dd><%= @home.street %></dd>

  <dt>City:</dt>
  <dd><%= @home.city %></dd>

  <dt>State:</dt>
  <dd><%= @home.state %></dd>

  <dt>Zipcode:</dt>
  <dd><%= @home.zipcode %></dd>

  <dt>Lat:</dt>
  <dd><%= @home.lat %></dd>

  <dt>Lng:</dt>
  <dd><%= @home.lng %></dd>

</dl>